/**
 * Iconos: un solo punto de importación para poder cambiar de librería.
 * Phosphor, peso "regular" en toda la app. La build SSR funciona en Server y Client Components.
 */
export {
  AirplaneTilt as IconPlane,
  ArrowRight as IconArrowRight,
  ArrowUpRight as IconExternal,
  Barbell as IconGym,
  Bed as IconBed,
  Bus as IconBus,
  CalendarCheck as IconCalendar,
  Car as IconCar,
  ChartBar as IconChart,
  ChatText as IconChat,
  Check as IconCheck,
  DotsThreeOutline as IconOther,
  DownloadSimple as IconDownload,
  ForkKnife as IconFood,
  Globe as IconGlobe,
  GraduationCap as IconStudy,
  House as IconHouse,
  Info as IconInfo,
  Key as IconKey,
  Laptop as IconLaptop,
  List as IconMenu,
  LockSimple as IconLock,
  MagnifyingGlass as IconSearch,
  MapPin as IconPin,
  Motorcycle as IconMoto,
  PawPrint as IconPet,
  PencilSimpleLine as IconPen,
  Plus as IconPlus,
  Scales as IconScales,
  ShareNetwork as IconShare,
  ShieldCheck as IconShield,
  Stack as IconStack,
  Tag as IconTag,
  Ticket as IconTicket,
  Train as IconTrain,
  Tram as IconTram,
  Trash as IconTrash,
  Van as IconVan,
  Wallet as IconWallet,
  WarningCircle as IconWarning,
  X as IconClose,
} from "@phosphor-icons/react/dist/ssr";
